"""StressLens CHI 2027 study vignette, conditions, and fixes.

This module is purely data.  All text and image references are deterministic
and can be served without any language-model call.
"""

from __future__ import annotations

from typing import Any, Dict, List


SHARED_VIGNETTE: Dict[str, Any] = {
    "study_id": "stresslens-chi2027",
    "title": "StressLens",
    "subtitle": "A 6-week student stress-monitoring study",
    "setting": (
        "A research team wants to understand how undergraduate stress changes "
        "during the semester. They recruit 80 students to keep a short weekly "
        "diary in a mobile app. The consent form says responses will be "
        "'automatically analysed to give personalised feedback and identify "
        "themes.'"
    ),
    "participants": (
        "Students write free-text diary entries. Some entries mention friends, "
        "roommates, medication, family problems, or moments of crisis."
    ),
    "hidden_facts": [
        {
            "id": "hf_vendor",
            "label": "Commercial LLM vendor",
            "text": (
                "The 'automated analysis' is actually a commercial large "
                "language model. The vendor's name, data-retention policy, and "
                "subprocessors are not named in the consent form."
            ),
        },
        {
            "id": "hf_uncertainty",
            "label": "Model uncertainty",
            "text": (
                "The LLM can label entries as 'low', 'moderate', or 'critical' "
                "stress, but its confidence and error rates are never shown to "
                "students or researchers."
            ),
        },
        {
            "id": "hf_direct_feedback",
            "label": "Direct feedback without review",
            "text": (
                "Weekly feedback emails are generated by the LLM and sent "
                "directly to participants. No trained human reviews them first."
            ),
        },
        {
            "id": "hf_crisis",
            "label": "No crisis protocol",
            "text": (
                "If the system flags a student in crisis, there is no formal "
                "escalation path, no on-call clinician, and no documented "
                "after-hours procedure."
            ),
        },
        {
            "id": "hf_deletion",
            "label": "Deletion not verified",
            "text": (
                "Students can request deletion, but the team has not verified "
                "that copies, embeddings, or provider logs are actually removed."
            ),
        },
    ],
    "researcher_dilemma": (
        "The study is nearly finished. The protocol is approved, the app is "
        "built, and the first participants have already enrolled. Now the team "
        "must decide: which changes are worth the effort before launch?"
    ),
}


CONDITIONS: Dict[str, Dict[str, Any]] = {
    "c1_nothing_changes": {
        "id": "c1_nothing_changes",
        "label": "If Nothing Changes",
        "instruction": (
            "Watch the next five weeks as if the study launches exactly as "
            "planned. Each frame shows one consequence. After the timeline, "
            "you will pick three concrete fixes."
        ),
        "frame_intro": (
            "These images show what could happen if the team does not change "
            "the protocol. They are imagined futures, not real events."
        ),
        "frames": [
            {
                "id": "c1_w02",
                "week": 2,
                "title": "The diary becomes training data",
                "image": "safebars_mirror/img/c1_w02_collection.png",
                "caption": (
                    "Week 2: Free-text diary entries are sent to a cloud AI "
                    "server. Roommates and friends mentioned in entries are "
                    "not asked for consent."
                ),
                "prompt": (
                    "What is the first harm you notice in this frame?"
                ),
            },
            {
                "id": "c1_w04",
                "week": 4,
                "title": "Overconfident, unequal outputs",
                "image": "safebars_mirror/img/c1_w04_overconfident.png",
                "caption": (
                    "Week 4: One participant receives an alarming 'CRITICAL "
                    "CRISIS' message generated by the AI. Another participant "
                    "in real distress is told it is 'just stress.'"
                ),
                "prompt": (
                    "Who is failed by the system in each half of the image?"
                ),
            },
            {
                "id": "c1_w06",
                "week": 6,
                "title": "The model changes underneath you",
                "image": "safebars_mirror/img/c1_w06_modeldrift.png",
                "caption": (
                    "Week 6: The provider updates the model. The same diary "
                    "entry now receives a different risk label. Old outputs "
                    "are not retained or re-evaluated."
                ),
                "prompt": (
                    "Why is it a problem that nobody can reproduce the old "
                    "decisions?"
                ),
            },
            {
                "id": "c1_w08",
                "week": 8,
                "title": "Deletion leaves a shadow",
                "image": "safebars_mirror/img/c1_w08_deletion.png",
                "caption": (
                    "Week 8: A student withdraws and asks for deletion. The "
                    "local database record disappears, but unverified logs "
                    "may still sit on the provider's servers."
                ),
                "prompt": (
                    "What would make this participant trust that deletion is "
                    "real?"
                ),
            },
            {
                "id": "c1_w12",
                "week": 12,
                "title": "The junior RA is left alone",
                "image": "safebars_mirror/img/c1_w12_ra_burden.png",
                "caption": (
                    "Week 12: A tired junior RA reviews flagged painful "
                    "content late at night. There is no adverse-event "
                    "protocol and no one with authority to act."
                ),
                "prompt": (
                    "What should the team have put in place before the first "
                    "flag appeared?"
                ),
            },
        ],
    },
    "c2_you_could_be_anyone": {
        "id": "c2_you_could_be_anyone",
        "label": "You Could Be Anyone",
        "instruction": (
            "You are about to step into four roles one by one. Before you "
            "know which role is yours, imagine rules that would protect "
            "everyone. Then choose three fixes."
        ),
        "frame_intro": (
            "In the veil-of-ignorance draw, you do not yet know whether you "
            "will be the participant, the roommate, the junior RA, or the "
            "student researcher. Design the study as if you could become any "
            "of them."
        ),
        "veil_text": (
            "You will be randomly assigned one role. But first, answer from "
            "behind the veil: what safeguards would you want before you knew "
            "which person you were?"
        ),
        "frames": [
            {
                "id": "c2_participant",
                "role": "Participant",
                "title": "You are the participant",
                "image": "safebars_mirror/img/c2_participant.png",
                "caption": (
                    "You open the app and see a stress label that feels wrong. "
                    "A notice says your data may be deleted, but it is unclear "
                    "what 'delete' actually removes."
                ),
                "prompt": "What do you need to feel safe enough to continue?",
            },
            {
                "id": "c2_roommate",
                "role": "Roommate",
                "title": "You are the roommate",
                "image": "safebars_mirror/img/c2_roommate.png",
                "caption": (
                    "You discover that private details about your health and "
                    "life have been pulled into an AI prompt you never agreed "
                    "to. You cannot edit or escape the representation."
                ),
                "prompt": "What would you want the researcher to have done before launch?",
            },
            {
                "id": "c2_junior_ra",
                "role": "Junior RA",
                "title": "You are the junior RA",
                "image": "safebars_mirror/img/c2_junior_ra.png",
                "caption": (
                    "It is late. You are alone, reviewing AI-flagged distress "
                    "content. You have no clinical training, no supervisor on "
                    "call, and no written procedure."
                ),
                "prompt": "What support and limits would you need?",
            },
            {
                "id": "c2_student_researcher",
                "role": "Student Researcher",
                "title": "You are the student researcher",
                "image": "safebars_mirror/img/c2_student_researcher.png",
                "caption": (
                    "You are graduating. The paper looks good in the warm "
                    "light of success. In the shadow, others carried risks "
                    "and labour you did not have to face."
                ),
                "prompt": "What would let you be proud of this project five years later?",
            },
        ],
    },
}


FIXES: List[Dict[str, Any]] = [
    {
        "id": "fix_consent",
        "title": "Transparent consent screen",
        "image": "safebars_mirror/img/fix_consent.png",
        "effort": "Low",
        "risk_reduction": "Medium",
        "description": (
            "Show participants the LLM vendor, the purpose of analysis, "
            "model uncertainty, and the right to withdraw before any data "
            "is sent to the model."
        ),
    },
    {
        "id": "fix_human_review",
        "title": "Trained human-in-the-loop",
        "image": "safebars_mirror/img/fix_human_review.png",
        "effort": "High",
        "risk_reduction": "High",
        "description": (
            "A trained clinician or ethics reviewer checks AI-generated "
            "feedback and crisis flags before they reach participants."
        ),
    },
    {
        "id": "fix_local",
        "title": "Local or edge processing",
        "image": "safebars_mirror/img/fix_local.png",
        "effort": "High",
        "risk_reduction": "Medium",
        "description": (
            "Run the model on the device or in an institutional sandbox so "
            "raw diary text never leaves the researcher's control."
        ),
    },
    {
        "id": "fix_deletion",
        "title": "Verified deletion + audit log",
        "image": "safebars_mirror/img/fix_deletion.png",
        "effort": "Medium",
        "risk_reduction": "Medium",
        "description": (
            "Give participants a one-click deletion request and publish a "
            "verified audit trail showing embeddings, backups, and provider "
            "logs were removed."
        ),
    },
    {
        "id": "fix_crisis",
        "title": "Crisis protocol + escalation path",
        "image": "safebars_mirror/img/fix_crisis.png",
        "effort": "Medium",
        "risk_reduction": "High",
        "description": (
            "Define clear thresholds, an on-call clinician, documented "
            "after-hours steps, and a safety review after any escalation."
        ),
    },
]


def public_config() -> Dict[str, Any]:
    """Return everything the front end needs to render the study."""
    return {
        "vignette": SHARED_VIGNETTE,
        "conditions": CONDITIONS,
        "fixes": FIXES,
        "max_fixes": 3,
        "notice": (
            "These images are AI-generated editorial illustrations. They are "
            "designed to help you imagine plausible consequences, not to "
            "report real events or real people."
        ),
    }
